## Integration configuration.
#[integration]
## Payload marshaler.
##
## This defines how the MQTT payloads are encoded. Valid options are:
## * protobuf:  Protobuf encoding
## * json:      JSON encoding (for debugging)
#marshaler="protobuf"


# See https://www.chirpstack.io/gateway-bridge/install/config/ for a full
# configuration example and documentation.

# # Passed as environment variables from compose file.
#[integration.mqtt.auth.generic]
#servers=["tcp://mosquitto:1883"]
#username=""
#password=""

[integration.mqtt]
event_topic_template="in865/gateway/{{ .GatewayID }}/event/{{ .EventType }}"
state_topic_template="in865/gateway/{{ .GatewayID }}/state/{{ .StateType }}"
command_topic_template="in865/gateway/{{ .GatewayID }}/command/#"
